src/Entity/DetallesReserva.php
<?php

namespace App\Entity;

use App\Repository\DetallesReservaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DetallesReservaRepository::class)]
class DetallesReserva
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $cantidad = 0;

    #[ORM\Column]
    private ?int $total_reserva = null;

    #[ORM\Column]
    private ?int $cantidad_adultos = 1;

    #[ORM\Column(nullable: true)]
    private ?int $cantidad_kids = 0;

    #[ORM\ManyToOne(inversedBy: 'detallesReserva', cascade: ['persist'])]
    private ?Tour $tour = null;

    #[ORM\ManyToOne(inversedBy: 'detallesReserva')]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_evento = null;

    #[ORM\ManyToMany(targetEntity: Reserva::class, inversedBy: 'detallesReservas')]
    #[ORM\JoinTable(name: 'detalles_reserva_reserva')]
    private Collection $reservas;

    #[ORM\OneToMany(mappedBy: 'detallesReserva', targetEntity: Evento::class)]
    private Collection $eventos;

    public function __construct()
    {
        $this->fecha_evento = new \DateTime();
        $this->reservas = new ArrayCollection();
        $this->eventos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(int $cantidad): static
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getTotalReserva(): ?int
    {
        return $this->total_reserva;
    }

    public function setTotalReserva(int $totalReserva): static
    {
        $this->total_reserva = $totalReserva;

        return $this;
    }

    /**
     * @return Collection<int, reserva>
     */
    public function getReservas(): Collection
    {
        return $this->reservas;
    }

    public function addReserva(Reserva $reserva): self
    {
        if (!$this->reservas->contains($reserva)) {
            $this->reservas[] = $reserva;
        }

        return $this;
    }

    public function removeReserva(Reserva $reserva): self
    {
        $this->reservas->removeElement($reserva);

        return $this;
    }

    public function getCantidadAdultos(): ?int
    {
        return $this->cantidad_adultos;
    }

    public function setCantidadAdultos(int $cantidad_adultos): static
    {
        $this->cantidad_adultos = $cantidad_adultos;

        return $this;
    }

    public function getCantidadKids(): ?int
    {
        return $this->cantidad_kids;
    }

    public function setCantidadKids(?int $cantidad_kids): static
    {
        $this->cantidad_kids = $cantidad_kids;

        return $this;
    }

    public function getTour(): ?Tour
    {
        return $this->tour;
    }

    public function setTour(?Tour $tour): static
    {
        $this->tour = $tour;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getFechaEvento(): ?\DateTimeInterface
    {
        return $this->fecha_evento;
    }

    public function setFechaEvento(\DateTimeInterface $fecha_evento): static
    {
        $this->fecha_evento = $fecha_evento;

        return $this;
    }

    /**
     * @return Collection<int, Evento>
     */
    public function getEventos(): Collection
    {
        return $this->eventos;
    }

    public function addEvento(Evento $evento): static
    {
        if (!$this->eventos->contains($evento)) {
            $this->eventos->add($evento);
            $evento->setDetallesReserva($this);
        }

        return $this;
    }

    public function removeEvento(Evento $evento): static
    {
        if ($this->eventos->removeElement($evento)) {
            // set the owning side to null (unless already changed)
            if ($evento->getDetallesReserva() === $this) {
                $evento->setDetallesReserva(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->fecha_evento->format('Y-m-d');
    }
}

src/Entity/Tour.php
<?php

namespace App\Entity;

use App\Repository\TourRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TourRepository::class)]
class Tour
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titulo = null;

    #[ORM\Column(length: 255)]
    private ?string $imagen = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descripcion_larga = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descripcion_corta = null;

    #[ORM\Column]
    private ?float $precio = null;

    #[ORM\Column]
    private ?bool $estado = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\OneToMany(mappedBy: 'tour', targetEntity: Reserva::class)]
    private Collection $reservas;

    #[ORM\OneToMany(mappedBy: 'tour', targetEntity: Slider::class)]
    private Collection $sliders;

    #[ORM\OneToMany(mappedBy: 'tour', targetEntity: DetallesReserva::class)]
    private Collection $detallesReserva;

    #[ORM\OneToMany(mappedBy: 'tour', targetEntity: Evento::class)]
    private Collection $eventos;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $hora_inicio = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $hora_fin = null;

    public function __construct()
    {
        $this->reservas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): static
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->imagen;
    }

    public function setImagen(string $imagen): static
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getDescripcionLarga(): ?string
    {
        return $this->descripcion_larga;
    }

    public function setDescripcionLarga(string $descripcion_larga): static
    {
        $this->descripcion_larga = $descripcion_larga;

        return $this;
    }

    public function getDescripcionCorta(): ?string
    {
        return $this->descripcion_corta;
    }

    public function setDescripcionCorta(string $descripcion_corta): static
    {
        $this->descripcion_corta = $descripcion_corta;

        return $this;
    }

    public function getPrecio(): ?float
    {
        return $this->precio;
    }

    public function setPrecio(float $precio): static
    {
        $this->precio = $precio;

        return $this;
    }

    public function isEstado(): ?bool
    {
        return $this->estado;
    }

    public function setEstado(bool $estado): static
    {
        $this->estado = $estado;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    /**
     * @return Collection<int, Reserva>
     */
    public function getReservas(): Collection
    {
        return $this->reservas;
    }

    public function addReserva(Reserva $reserva): static
    {
        if (!$this->reservas->contains($reserva)) {
            $this->reservas->add($reserva);
            $reserva->setTour($this);
        }

        return $this;
    }

    public function removeReserva(Reserva $reserva): static
    {
        if ($this->reservas->removeElement($reserva)) {
            // set the owning side to null (unless already changed)
            if ($reserva->getTour() === $this) {
                $reserva->setTour(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Slider>
     */
    public function getSliders(): Collection
    {
        return $this->sliders;
    }

    public function addSlider(Slider $slider): static
    {
        if (!$this->sliders->contains($slider)) {
            $this->sliders->add($slider);
            $slider->setTour($this);
        }

        return $this;
    }

    public function removeSlider(Slider $slider): static
    {
        if ($this->sliders->removeElement($slider)) {
            // set the owning side to null (unless already changed)
            if ($slider->getTour() === $this) {
                $slider->setTour(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, DetallesReserva>
     */
    public function getDetallesReserva(): Collection
    {
        return $this->detallesReserva;
    }

    public function addDetallesReserva(DetallesReserva $detallesReserva): static
    {
        if (!$this->detallesReserva->contains($detallesReserva)) {
            $this->detallesReserva->add($detallesReserva);
            $detallesReserva->setTour($this);
        }

        return $this;
    }

    public function removeDetallesReserva(DetallesReserva $detallesReserva): static
    {
        if ($this->detallesReserva->removeElement($detallesReserva)) {
            // set the owning side to null (unless already changed)
            if ($detallesReserva->getTour() === $this) {
                $detallesReserva->setTour(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Evento>
     */
    public function getEventos(): Collection
    {
        return $this->eventos;
    }

    public function addEvento(Evento $evento): static
    {
        if (!$this->eventos->contains($evento)) {
            $this->eventos->add($evento);
            $evento->setTour($this);
        }

        return $this;
    }

    public function removeEvento(Evento $evento): static
    {
        if ($this->eventos->removeElement($evento)) {
            // set the owning side to null (unless already changed)
            if ($evento->getTour() === $this) {
                $evento->setTour(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->titulo;
    }


    public function getHoraInicio(): ?\DateTimeInterface
    {
        return $this->hora_inicio;
    }

    public function setHoraInicio(\DateTimeInterface $hora_inicio): static
    {
        $this->hora_inicio = $hora_inicio;

        return $this;
    }

    public function getHoraFin(): ?\DateTimeInterface
    {
        return $this->hora_fin;
    }

    public function setHoraFin(\DateTimeInterface $hora_fin): static
    {
        $this->hora_fin = $hora_fin;

        return $this;
    }
}

templates/app/show.html.twig
{% extends 'base.html.twig' %} {% block title %} Devis commande {% endblock %}
{% block body %}
<div id="main-container" class="container-fluid my-3">
  {% for message in app.flashes('danger') %}
  <div class="alert alert-danger text-center w-50 mx-auto my-2">
    {{ message }}
  </div>
  {% endfor %}
<section class="table__section">
  <table class="table">
    <thead class="table__head">
      <tr>
        <th class="align-middle">Precio</th>
        <th class="align-middle">Adultos</th>
        <th class="align-middle">Niños</th>
        <th class="align-middle">Fecha</th>
        <th class="align-middle">Tour</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="text-center align-middle">
          <img
            src="{{ asset('uploads/images/' ~ tour.imagen) }}"
            alt="{{ tour.titulo }}"
            style="object-fit: cover"
            width="100%"
            height="100"
          />
          <div class="table__titulo">
            {{ tour.titulo | title }} : {{ tour.horaInicio|date("H:i") }} h - {{ tour.horaFin|date("H:i") }} h
            </div>
        </td>
        <td class="table__
        precio">
          {% if tour.precio == 0 %}
          <p><span>Free Tour</span></p>
          {% else %}
          <p>{{ tour.precio/100|number_format(2, '.') }} €</p>
          {% endif %}
        </td>

        {% if app.user %}
        {{
          form_start(form, { attr: { novalidate: "novalidate" } })
        }}
        <td class="text-center align-middle">
          {{ form_row(form.cantidad_adultos) }}
        </td>

        <td class="text-center align-middle">
          {{ form_row(form.cantidad_kids) }}
        </td>
        <td class="text-center align-middle">
          {{ form_row(form.fecha_evento, {'attr': {'name': 'fechaEvento'}}) }}
        </td>
      </tr>
    </tbody>
    {#
    <tfoot>
      <tr>
        <td class="text-left align-middle">
          {% if totalReserva == 0 %}
          <p><span>Total: Free Tour</span></p>
          {% else %}
          <p>Total: {{ totalReserva / 100 | number_format(2, '.') }} €</p>
          {% endif %}
        </td>
      </tr>
    </tfoot>
    #}
  </table>
  
  <div class="row col-12">
    <div class="col-6">
      <div class="buttons">
          <a href="#" class="btn-secondary me-3">
            Vaciar el carrito
          </a>
          <a href="{{ path('home') }}" class="btn-tertiary"> Ver más tours </a>
        </div>
      </div>
      <div class="col-6 text-end">
        <button type="submit" class="btn-primary me-3">Validar pedido</button>
        

        {{ form_end(form) }}
      </div>
    </div>
  </div>
  <!-- Fin del bloque de formulario de datos personales -->
  
  
  {% else %}
  <p>Tu carrito está vacío</p>
  {% endif %}
</div>
</section>
{% endblock %} 

templates/app/tour.html.twig
{% extends 'base.html.twig' %} {% block title %} {% for slider in sliders %}
{{ slider.titulo }}
{% endfor %} {% endblock %} {% block header %} {% endblock %} {% block body %}
<div class="fixed-nav">{% include 'nav/_menu_nav.html.twig' %}</div>
<div class="carousel-container">
  <div
    id="carouselExampleIndicators"
    class="carousel slide"
    data-bs-ride="carousel"
  >
    <div class="carousel-inner">
      {% for slider in sliders %}
      <div class="carousel-item{% if loop.first %} active{% endif %}">
        <div
          class="card-image-slider"
          style="background-image: linear-gradient(rgba(0, 0, 0, 0.316), transparent), url('{{ asset('uploads/images/' ~ slider.imagen) }}'); background-size: cover; background-position: center;"
        >
          <div class="content-slider">
            <h3 class="animation content-slider-title">
              {{ slider.titulo }}
            </h3>
            <h2 class="animation content-slider-subtitle">
              {{ tour.titulo }}
            </h2>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <button
      class="carousel-control-prev"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button
      class="carousel-control-next"
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<div class="menu__detalle-tour">
  <div class="detalle-tour">
    <ul>
      <li>
        <a
          href="#descripcion"
          id="selected
               "
          >Descripcion</a
        >
      </li>
      <li><a href="#precio">Precios</a></li>
      <li><a href="#detalles">Detalles</a></li>
      <li><a href="#cancelacion">Cancelaciones</a></li>
      <li><a href="#encuentro">Punto de encuentro</a></li>
      <li><a href="#">Opiniones</a></li>
    </ul>
  </div>
</div>
<div id="container-detalles">
  <div id="descripcion" class="container-detalles">
    <h3>{{ tour.titulo }}</h3>
    <div class="detalle-descripcion">
      <p>{{ tour.descripcionCorta }}</p>
      <div class="descripcion-hidden">
        <p>{{ tour.descripcionLarga | raw }}</p>
      </div>
      <div class="descripcion-container">
        <a href="#" id="mostrar-link" class="btn-description"
          >Ver descripción completa</a
        >
      </div>
      <a href="#" id="ocultar-link" class="descripcion-hidden"
        >Ocultar descripción</a
      >
    </div>
    <hr />
    <div id="precio" class="detalle-precio">
      <h3>Precio</h3>
      <p>
        Los free tours no tienen un precio fijo. Cada persona valora la labor
        del guía y, al finalizar el tour, entrega el importe que considere a su
        voluntad en función de su satisfacción.
      </p>
    </div>
    <hr />
    <div id="detalles" class="detalle-general">
      <h3>Detalles</h3>
      <div>
        <div class="detalle-duracion">
          <div class="detalle-titulo">
            <i class="fas fa-clock"></i>
            <h5>Duracion</h5>
          </div>
          <p>1h 30m - 2h</p>
        </div>
        <hr />
        <div class="detalle-idioma">
          <div class="detalle-titulo">
            <i class="fas fa-comment"></i>
            <h5>Idioma</h5>
          </div>
          <p>La actividad se realiza con un guia que habla espanol</p>
        </div>

        <hr />
        <div class="detalle-incluido">
          <div class="detalle-titulo">
            <i class="fas fa-check"></i>
            <h5>Incluido</h5>
          </div>
          <p>Guia en espanol</p>
        </div>
        <hr />
        <div class="detalle-noincluido">
          <div class="detalle-titulo">
            <i class="fas fa-ban"></i>
            <h5>No incluido</h5>
          </div>
          <p>Propinas</p>
        </div>
        <hr />
        <div class="detalle-reservar">
          <div class="detalle-titulo">
            <i class="fas fa-calendar"></i>
            <h5>Cuando reservar</h5>
          </div>
          <p>Puedes reservar hasta 30 minutos antes de que comience el tour</p>
        </div>
        <hr />
        <div class="detalle-accesibilidad">
          <div class="detalle-titulo">
            <i class="fas fa-wheelchair"></i>
            <h5>Accesibilidad</h5>
          </div>
          <p>No es accesible en silla de ruedas</p>
        </div>
        <hr />
        <div class="detalle-mascotas">
          <div class="detalle-titulo">
            <i class="fas fa-paw"></i>
            <h5>Mascotas</h5>
          </div>
          <p>No permitidas</p>
        </div>
        <hr />
        <div class="detalle-faq">
          <div class="detalle-titulo">
            <i class="fas fa-question"></i>
            <h5>Preguntas frecuentes</h5>
          </div>
        </div>
        <div class="detalle-faq-2">
          <ul>
            <li>
              <p><strong>Como hacer la reserva?</strong></p>
              <p>
                Para reservar el Free tour de leyendas y misterios de Paris,
                elige la fecha deseada y completa el formulario, indicando el
                numero de participantes. La confirmacion es inmediata.
              </p>
            </li>
            <li>
              <p>
                <strong>Se necesita un numero minimo de participantes?</strong>
              </p>
              <p>
                El numero minimo de participantes es de una persona, asi que si
                es tu caso apuntate y disfruta de un rato agradable
              </p>
            </li>
            <li>
              <p>
                Para cualquier otra duda, {#
                <a href="{{ path('contacto') }}">contacta con nosotros</a> #}
              </p>
            </li>
          </ul>
        </div>
        <hr />
        <div id="cancelacion" class="detalle-cancelacion">
          <h3>Cancelacion gratuita</h3>
          <p>
            Si no vas a poder asistir al tour, por favor, cancela la reserva, si
            no, el guía te estará esperando.
          </p>
        </div>
        <hr />
        <div id="encuentro" class="detalle-encuentro">
          <div class="meeting-point">
            <h3>Punto de encuentro</h3>
            <h5><strong>Donde termina la actividad?</strong></h5>
          </div>
          <div class="ubicacion">
            <div class="detalle-location">
              <i class="fas fa-map-marker-alt"></i>
              <p>Place de cité</p>
            </div>
            <div class="detalle-location">
              <i class="fas fa-map-marker-alt"></i>
              <p>Plaza del ayuntamiento</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {#
  <div class="calendar">
    <img
      src="{{ asset('uploads/images/montmartre.jpg') }}"
      alt=""
      width="250"
      height="350"
    />
  </div>
  #}
</div>
{% endblock %} {% block javascripts %}
<script>
  const navBar1 = document.querySelector("#navigation");
const menuBtn = document.querySelector(".menu-btn");
const closeBtn = document.querySelector(".close-btn");
const menuMobile = document.querySelector(".menu-mobile");
const navBarSpan = document.querySelector(".logo a span");
const navBarElem = document.querySelector("nav ul li a");
// const navBarUserName = document.querySelector(".icon-nav");   
const mobileLinks = document.querySelectorAll(".menu-mobile li");

menuBtn.addEventListener("click", () => {
  menuBtn.style.display = "none";
  closeBtn.style.display = "block";
  closeBtn.style.color = 'white';
  menuMobile.classList.add('active');
  navBar1.style.backgroundColor = "#18BB9C";
  navBarElem.style.color = "#000";
  navBarSpan.style.color = "#000";
  // navBarUserName.style.color = "#000";
});

closeBtn.addEventListener("click", () => {
  menuBtn.style.display = "block";
  closeBtn.style.display = "none";
  menuMobile.classList.remove('active');
  if (scrollY > 0) {
    navBar1.style.backgroundColor = "#18BB9C";
    navBarElem.style.color = "#000";
    navBarSpan.style.color = "#000";
    // navBarUserName.style.color = "#000";
  } else {
    // Solo cambia el color de fondo si el ancho de la pantalla es menor a 970px
    if (window.innerWidth < 970) {
      navBar1.style.backgroundColor = "#18BB9C";
      navBarElem.style.color = "#000";
      navBarSpan.style.color = "#000";
      // navBarUserName.style.color = "#000";
    } else {
      navBar1.style.backgroundColor = "#18BB9C";
      navBarElem.style.color = "#000";
      navBarSpan.style.color = "#000";
      // navBarUserName.style.color = "#000";
    }
  }
});

function handleResize() {
  if (window.innerWidth >= 970) {
    // Si el ancho de la pantalla es mayor o igual a 970px
    menuBtn.style.display = "none";
    closeBtn.style.display = "none";
    navBarElem.style.color = "#18BB9C";
    navBarSpan.style.color = "#18BB9C";
    navBar1.style.backgroundColor = "transparent";
  } else {
    // Si el ancho de la pantalla es menor de 970px
    menuBtn.style.display = "block";
    closeBtn.style.display = "none";
    navBar1.style.backgroundColor = "#18BB9C";
    navBarElem.style.color = "#000";
    navBarSpan.style.color = "#000";
  }
}

// Ejecutar handleResize al cargar la página
handleResize();

// Ejecutar handleResize cada vez que se cambie el tamaño de la pantalla
window.addEventListener("resize", handleResize);

mobileLinks.forEach(link => (link.addEventListener("click", () => {
  menuMobile.classList.remove('active');
  menuBtn.style.display = "block";
  closeBtn.style.display = "none";
})));


//* ------------- Logique pour que le fond du navBar change a partir d'un petit scroll d'ecran, et aussi la couleur de certains elements qui se trouvent dans la navBar, et a partir de 300px de scroll la navBar disparait en se montre a noubeau quand on scroll vers la haut ----------------

window.addEventListener("scroll", () => {
if (window.scrollY > 0 && window.scrollY < 300) {
 if (window.innerWidth >= 970) {
   navBar1.style.backgroundColor = "#18BB9C";
   navBarElem.style.color = "#000";
   navBarSpan.style.color = "#000";
  //  navBarUserName.style.color = "#000";
 } else {
   navBar1.style.backgroundColor = "#18BB9C";
   navBarElem.style.color = "#000";
   navBarSpan.style.color = "#000";
  //  navBarUserName.style.color = "#000";
 }
} else if (window.scrollY > 300) {
 navBar1.style.display = "none";
} else {
 navBar1.style.backgroundColor = "transparent";
 navBarElem.style.color = "#18BB9C";
 navBarSpan.style.color = "#18BB9C";
//  navBarUserName.style.color = "#000";
}
});

let prevScrollY = window.scrollY;

window.addEventListener("scroll", () => {
const currentScrollY = window.scrollY;

if (currentScrollY < prevScrollY) {
 navBar1.style.display = "flex";   
}

prevScrollY = currentScrollY;
});

// Ejecutamos la función al cargar la página
window.dispatchEvent(new Event("scroll"));
</script>
{{ encore_entry_script_tags("js/tour") }}

{% endblock %}

templates/app/validar_reserva.html.twig
{% extends 'base.html.twig' %} {% block title %} Devis reserva {% endblock %} {%
block body %}
<div id="main-container" class="container my-5">
  {% for message in app.flashes('success') %}
  <div class="alert alert-success text-center w-50 mx-auto my-2">
    {{ message }}
  </div>
  {% endfor %}
  <div class="titulo__reservas">
    <h2>Resumen de reserva</h2>
  </div>
  <div class="reserva-container">
    <img
      src="{{ asset('uploads/images/' ~ tour.imagen) }}"
      alt="{{ tour.titulo }}"
      width="350px"
      height="280px"
    />

    {% if app.user.reservas is not empty %}
    <div class="detalles-reserva">
      <ul>
        <h3>{{ tour.titulo }}</h3>
        <li>
          <p class="card-title">N°. reserva: {{ reserva.referencia }}</p>
        </li>

        {% for detalle in reserva.detallesReservas %}
        <li>
          <p class="card-title">
            Fecha del tour: {{ detalle.fechaEvento|date('d/m/y') }}
          </p>
        </li>
        <li>
          <p class="card-title">Adultos: {{ detalle.cantidadAdultos }}</p>
        </li>
        <li>
          <p class="card-title">Niños: {{ detalle.cantidadKids }}</p>
        </li>

        {% if detalle.totalReserva == 0 %}
        <li>
          <p class="card-title">Total: Free Tour</p>
        </li>
        {% else %}
        <li>
          <p class="card-title">
            Total: {{ detalle.totalReserva/100|number_format(2, '.') }} €
          </p>
        </li>
        {% if tour.precio != 0 %}
        <div class="button">
          <a href="#" class="btn-primary me-3">Proceder al pago</a>
        </div>
        {% endif %} {% endif %} {% endfor %}
      </ul>
    </div>
    {% else %}
    <p>No hay reservas disponibles.</p>
    {% endif %}
  </div>
</div>
{% endblock %} {% block javascripts %}
<script>
  const selectForm = document.querySelector("#selectDatosClienteReserva");
  const optionsForm = document.querySelector("#optionsDatosClienteReserva");
  optionsForm.addEventListener("click", (event) => {
    event.stopPropagation(); // Elimina esta línea
  });

  selectForm.addEventListener("click", () => {
    selectForm.classList.toggle("active");
    optionsForm.classList.toggle("active");
    optionsForm.scrollIntoView({ behavior: "smooth", block: "start" });
  });
</script>
{% endblock %}